# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: lakekeeper
spec:
  interval: 1h
  chart:
    spec:
      chart: lakekeeper
      version: 0.9.0
      sourceRef:
        kind: HelmRepository
        name: lakekeeper
        namespace: flux-system
  install:
    remediation:
      retries: -1
    # https://github.com/lakekeeper/lakekeeper-charts/issues/81#issuecomment-2925285591
    disableWait: true
  upgrade:
    disableWait: true
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    catalog:
      dbMigrations:
        enabled: true
        extraInitContainers:
          - name: init-db-default
            image: ghcr.io/home-operations/postgres-init:18.2.0
            imagePullPolicy: IfNotPresent
            env:
              - name: INIT_POSTGRES_DBNAME
                value: lakekeeper_catalog
            envFrom:
              - secretRef:
                  name: lakekeeper-secret
    secretBackend:
      postgres:
        encryptionKeySecret: "lakekeeper-secret"
        encryptionKeySecretKey: "encryption-key"
    postgresql:
      enabled: false
    externalDatabase:
      type: postgres
      host_read: "postgres-rw.database.svc.cluster.local"
      host_write: "postgres-rw.database.svc.cluster.local"
      port: 5432
      database: lakekeeper_catalog
      user: catalog
      passwordSecret: "lakekeeper-secret"
      passwordSecretKey: "postgres-password"
    authz:
      backend: "openfga"
      openfga:
        endpoint: http://openfga.dev.svc.cluster.local:8081
    auth:
      # -- Configuration for the authentication of the catalog.
      # If `auth.oauth2.providerUri` is not set and `auth.kubernetes.enabled` is false,
      # authentication is disabled.
      oauth2:
        # -- If set, access to rest endpoints is secured via an external OIDC-capable IdP.
        # The IdP must expose `{provider_url}/.well-known/openid-configuration`
        # and the openid-configuration needs to have the jwks_uri and issuer defined.
        # For keycloak set: https://keycloak.local/realms/test
        # For Entra-ID set: https://login.microsoftonline.com/{your-tenant-id}/v2.0
        providerUri: "https://auth.toskbot.xyz/application/o/lakekeeper"
        # -- The expected Audience of the OIDC App of lakekeeper.
        # The aud (audience) claim of the JWT token must match this value. Typically this is
        # the Client ID.
        audience: "lakekeeper"
        # -- Additional allow OIDC issuers.
        # The issuer defined in the issuer field of the ``.well-known/openid-configuration``
        # is always trusted. `additionalIssuers` has no effect if `providerUri` is not set.
        additionalIssuers: []

        ui:
          # -- Client ID used for the Authorization Code Flow of the UI.
          # Required if Authentication is enabled.
          clientID: "9K14HbVe7lPexMUxaaFIWN61fvOltnp7gDyqdJYJ"
          # -- Space separated scopes to request
          scopes: "lakekeeper"
          # -- Resource to request
          # resource: ""
