---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./external-dns.yaml
  - ./bjw-s-labs.yaml
  - ./longhorn.yaml
  - ./cloudnative-pg.yaml
  - ./emqx.yaml
  - ./apache-spark.yaml
  - ./flink-operator.yaml
  - ./apache-yunikorn.yaml
  - ./temporal.yaml
  - ./lakekeeper.yaml
  - ./openfga.yaml
  - ./authentik.yaml
  - ./strimzi.yaml
  - ./knative-operator.yaml
