# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openfga
spec:
  interval: 1h
  chart:
    spec:
      chart: openfga
      version: 0.2.54
      sourceRef:
        kind: HelmRepository
        name: openfga
        namespace: flux-system
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    datastore:
      engine: postgres
      uri: "postgres://postgres-rw.database.svc.cluster.local:5432/openfga?sslmode=disable"
      existingSecret: openfga-secret
      secretKeys:
        usernameKey: postgres-username
        passwordKey: postgres-password
    migrate:
      extraInitContainers:
        - name: init-db-default
          image: ghcr.io/home-operations/postgres-init:18.2.0
          imagePullPolicy: IfNotPresent
          env:
            - name: INIT_POSTGRES_DBNAME
              value: openfga
          envFrom:
            - secretRef:
                name: openfga-secret
      annotations:
    serviceAccount:
      create: true
      annotations:
        helm.sh/hook: "pre-install"
        helm.sh/hook-weight: "-6"
